SELECT 
    d.ActionDate,
    ISNULL(COUNT(DISTINCT s.SecretId), 0) AS UniqueSecretsCount,
    ISNULL(COUNT(DISTINCT f.FolderId), 0) AS UniqueFoldersCount
FROM (
    SELECT DATEADD(DAY, n, DATEADD(DAY, -30, CAST(GETDATE() AS DATE))) AS ActionDate
    FROM (
        SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL
        SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL
        SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL
        SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL
        SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL
        SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL
        SELECT 30 UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34
    ) nums
    WHERE DATEADD(DAY, n, DATEADD(DAY, -30, CAST(GETDATE() AS DATE))) <= CAST(GETDATE() AS DATE)
) d
LEFT JOIN tbauditsecret a WITH (NOLOCK)
    ON CAST(a.DateRecorded AS DATE) = d.ActionDate
    AND a.Action NOT IN(
        'DEACTIVATE',
        'VIEW',
        'PASSWORD DISPLAYED',
        'PRIVATE KEY PASSPHRASE DISPLAYED',
        'EXPORT',
        'SECRET COPIED FROM',
        'SECRET CHECKED IN',
        'FILE SAVE')
LEFT JOIN tbsecret s WITH (NOLOCK)
    ON s.SecretId = a.SecretId
LEFT JOIN tbAuditFolder af WITH (NOLOCK)
    ON CAST(af.DateRecorded AS DATE) = d.ActionDate
    AND af.Action NOT IN ('MOVE', 'REPLICATION CONFLICT')
LEFT JOIN tbFolder f WITH (NOLOCK)
    ON f.FolderId = af.FolderId
GROUP BY d.ActionDate
ORDER BY d.ActionDate ASC
